name: Linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Python
        run: |
          pip install ruff
          ruff check src/backend/

      - name: Lint JavaScript
        run: |
          cd src/frontend
          npm install
          npm install --save-dev @typescript-eslint/parser
          npx eslint@8 app/ --ext .ts,.tsx --no-eslintrc --parser @typescript-eslint/parser --env es2020 --env browser --parser-options=ecmaVersion:2020,sourceType:module